/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe (public). */
        get: operations["MainController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user profile (provisioned by the auth guard). */
        get: operations["AuthController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the current user displayName / photoUrl. */
        patch: operations["AuthController_updateMe"];
        trace?: never;
    };
    "/api/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lifetime activity totals for the current user. */
        get: operations["StatsController_getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visible routes by scope (mine | member | public), cursor-paginated. */
        get: operations["RoutesController_list"];
        put?: never;
        /** Create a route from snapped GeoJSON; recomputes distance and auto-creates the default segment. */
        post: operations["RoutesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one route (owner/member, or anyone if public): geometry + segments + member count. */
        get: operations["RoutesController_getById"];
        put?: never;
        post?: never;
        /** Delete a route (owner only; cascades). */
        delete: operations["RoutesController_delete"];
        options?: never;
        head?: never;
        /** Update name/description/visibility or replace geometry (owner only). */
        patch: operations["RoutesController_update"];
        trace?: never;
    };
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user’s activities (cursor-paginated). */
        get: operations["ActivitiesController_listMine"];
        put?: never;
        /** Upsert a finished activity (client id + track + stats); builds the track and returns bestEfforts. */
        post: operations["ActivitiesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one activity (owner, or anyone when its route is public). */
        get: operations["ActivitiesController_getById"];
        put?: never;
        post?: never;
        /** Delete my activity (cascades points + efforts). */
        delete: operations["ActivitiesController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List activities recorded on a route (owner, JOINED member, or public route). */
        get: operations["RouteActivitiesController_listForRoute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite someone to a route by email (owner only) → membership INVITED. Links an existing User or holds the invite against the email. */
        post: operations["RouteMembersController_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a route’s members and their status (owner or JOINED member only). */
        get: operations["RouteMembersController_listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member (route owner) or leave the route (self). The owner cannot be removed. */
        delete: operations["RouteMembersController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user’s pending (INVITED) invites — their inbox. */
        get: operations["InvitesController_listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{inviteId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invite → JOINED (only the invitee may accept). */
        post: operations["InvitesController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{inviteId}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline an invite → DECLINED (only the invitee may decline). */
        post: operations["InvitesController_decline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/{segmentId}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranked best efforts on a segment (RANK() semantics), cursor-paginated, with an optional time window. */
        get: operations["SegmentLeaderboardController_getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/{segmentId}/leaderboard/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current user’s best effort + rank on a segment (even when off-page). */
        get: operations["SegmentLeaderboardController_getMyEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Leaderboard for a route’s default full-route segment (convenience), cursor-paginated. */
        get: operations["RouteLeaderboardController_getRouteLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routing/snap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snap a drawn polyline to roads via the local GraphHopper; returns a GeoJSON LineString + distance. Degrades to the unsnapped line (200) on routing failure. */
        post: operations["RoutingController_snap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{id}/live/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a route’s live session: verify membership, enforce the participant cap, mirror the RTDB membership index, and return RTDB paths + throttle policy. */
        post: operations["RouteLiveController_startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{id}/live/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Optional read-through of live participants (direct RTDB subscribe is preferred). Empty/offline when Firebase is not configured. */
        get: operations["RouteLiveController_listParticipants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MeResponseDto: {
            /**
             * @description Internal id (= Firebase uid).
             * @example firebase-uid-abc123
             */
            id: string;
            /** @example alice@example.com */
            email: string;
            /** @example Alice Runner */
            displayName?: Record<string, never> | null;
            /** @example https://example.com/avatars/alice.png */
            photoUrl?: Record<string, never> | null;
            /**
             * @description Whether the email is verified.
             * @example false
             */
            emailVerified: boolean;
            /** @example 2026-06-01T08:30:00.000Z */
            createdAt: string;
            /** @example 2026-06-01T08:30:00.000Z */
            updatedAt: string;
            /** @example 2026-06-01T08:30:00.000Z */
            lastSeenAt?: string | null;
        };
        UpdateMeRequestDto: {
            /** @example Alice Runner */
            displayName?: string;
            /** @example https://example.com/avatars/alice.png */
            photoUrl?: string;
        };
        StatsSummaryResponseDto: {
            /** @example 42 */
            activityCount: number;
            /**
             * @description Total distance in meters.
             * @example 210345.6
             */
            totalDistanceM: number;
            /**
             * @description Total moving duration in milliseconds (BigInt serialized as string).
             * @example 25620000
             */
            totalDurationMs: string;
            /**
             * @description Start time of the most recent activity, or null.
             * @example 2026-06-01T08:30:00.000Z
             */
            lastActivityAt?: string | null;
        };
        RouteGeometryRequestDto: {
            /**
             * @example LineString
             * @enum {string}
             */
            type: "LineString";
            /**
             * @description Ordered [lng, lat] coordinate pairs (WGS84); ≥ 2 points.
             * @example [
             *       [
             *         -122.401,
             *         37.78
             *       ],
             *       [
             *         -122.402,
             *         37.781
             *       ],
             *       [
             *         -122.403,
             *         37.782
             *       ]
             *     ]
             */
            coordinates: number[][];
        };
        RouteElevationRequestDto: {
            /**
             * @description Total elevation gain in meters.
             * @example 42.5
             */
            gainMeters: number;
            /**
             * @description Elevation chart samples: [{ distM, eleM }].
             * @example [
             *       {
             *         "distM": 0,
             *         "eleM": 34.2
             *       },
             *       {
             *         "distM": 1000,
             *         "eleM": 41.7
             *       },
             *       {
             *         "distM": 2000,
             *         "eleM": 38.1
             *       }
             *     ]
             */
            profile?: {
                distM?: number;
                eleM?: number;
            }[];
        };
        CreateRouteRequestDto: {
            /** @example Riverside loop */
            name: string;
            /** @example Flat 5k along the river path. */
            description?: string;
            /**
             * @example public
             * @enum {string}
             */
            visibility: "private" | "invite" | "public";
            geometry: components["schemas"]["RouteGeometryRequestDto"];
            /**
             * @description Advisory distance in meters; the server recomputes from geometry.
             * @example 5012.4
             */
            distanceMeters?: number;
            elevation: components["schemas"]["RouteElevationRequestDto"];
        };
        GeoJsonLineStringDto: {
            /**
             * @example LineString
             * @enum {string}
             */
            type: "LineString";
            /**
             * @description Ordered [lng, lat] coordinate pairs (WGS84).
             * @example [
             *       [
             *         -122.401,
             *         37.78
             *       ],
             *       [
             *         -122.402,
             *         37.781
             *       ],
             *       [
             *         -122.403,
             *         37.782
             *       ]
             *     ]
             */
            coordinates: number[][];
        };
        RouteResponseDto: {
            /** @example route-uuid-7f3a */
            id: string;
            /**
             * @description Owner User.id.
             * @example firebase-uid-abc123
             */
            ownerId: string;
            /** @example Riverside loop */
            name: string;
            /** @example Flat 5k along the river path. */
            description?: Record<string, never> | null;
            /** @description Route path as a GeoJSON LineString (WGS84). */
            geometry: components["schemas"]["GeoJsonLineStringDto"];
            /**
             * @description Route length in meters (recomputed via ST_Length on geography).
             * @example 5012.4
             */
            distanceM: number;
            /**
             * @description Total elevation gain in meters.
             * @example 42.5
             */
            elevationGainM?: Record<string, never> | null;
            /**
             * @description Elevation chart samples: [{ distM, eleM }].
             * @example [
             *       {
             *         "distM": 0,
             *         "eleM": 34.2
             *       },
             *       {
             *         "distM": 1000,
             *         "eleM": 41.7
             *       },
             *       {
             *         "distM": 2000,
             *         "eleM": 38.1
             *       }
             *     ]
             */
            elevationProfile?: {
                distM?: number;
                eleM?: number;
            }[] | null;
            /**
             * @description True when visibility is 'public'; drives the Explore feed.
             * @example true
             */
            isPublic: boolean;
            /** @example 2026-06-01T08:30:00.000Z */
            createdAt: string;
            /** @example 2026-06-01T08:30:00.000Z */
            updatedAt: string;
        };
        RouteDto: {
            /** @example route-uuid-7f3a */
            id: string;
            /**
             * @description Owner User.id.
             * @example firebase-uid-abc123
             */
            ownerId: string;
            /** @example Riverside loop */
            name: string;
            /** @example Flat 5k along the river path. */
            description?: Record<string, never> | null;
            /** @description Route path as a GeoJSON LineString (WGS84). */
            geometry: components["schemas"]["GeoJsonLineStringDto"];
            /**
             * @description Route length in meters (recomputed via ST_Length on geography).
             * @example 5012.4
             */
            distanceM: number;
            /**
             * @description Total elevation gain in meters.
             * @example 42.5
             */
            elevationGainM?: Record<string, never> | null;
            /**
             * @description Elevation chart samples: [{ distM, eleM }].
             * @example [
             *       {
             *         "distM": 0,
             *         "eleM": 34.2
             *       },
             *       {
             *         "distM": 1000,
             *         "eleM": 41.7
             *       },
             *       {
             *         "distM": 2000,
             *         "eleM": 38.1
             *       }
             *     ]
             */
            elevationProfile?: {
                distM?: number;
                eleM?: number;
            }[] | null;
            /**
             * @description True when visibility is 'public'; drives the Explore feed.
             * @example true
             */
            isPublic: boolean;
            /** @example 2026-06-01T08:30:00.000Z */
            createdAt: string;
            /** @example 2026-06-01T08:30:00.000Z */
            updatedAt: string;
        };
        RouteListResponseDto: {
            routes: components["schemas"]["RouteDto"][];
            /**
             * @description Cursor for the next page, or null when there are no more rows.
             * @example a1b2c3d4-e5f6-4789-a012-3456789abcde
             */
            nextCursor?: string | null;
        };
        SegmentDto: {
            /** @example segment-uuid-9c1b */
            id: string;
            /** @example route-uuid-7f3a */
            routeId: string | null;
            /** @example Riverside loop */
            name: string;
            path: components["schemas"]["GeoJsonLineStringDto"];
            /**
             * @description Segment length in meters (ST_Length over geography).
             * @example 5012.4
             */
            distanceM: number;
            /**
             * @description Match tolerance at the segment start, meters.
             * @example 25
             */
            startBuffer: number;
            /**
             * @description Match tolerance at the segment end, meters.
             * @example 25
             */
            endBuffer: number;
            /** @example 2026-06-01T08:30:00.000Z */
            createdAt: string;
        };
        RouteDetailResponseDto: {
            /** @example route-uuid-7f3a */
            id: string;
            /**
             * @description Owner User.id.
             * @example firebase-uid-abc123
             */
            ownerId: string;
            /** @example Riverside loop */
            name: string;
            /** @example Flat 5k along the river path. */
            description?: Record<string, never> | null;
            /** @description Route path as a GeoJSON LineString (WGS84). */
            geometry: components["schemas"]["GeoJsonLineStringDto"];
            /**
             * @description Route length in meters (recomputed via ST_Length on geography).
             * @example 5012.4
             */
            distanceM: number;
            /**
             * @description Total elevation gain in meters.
             * @example 42.5
             */
            elevationGainM?: Record<string, never> | null;
            /**
             * @description Elevation chart samples: [{ distM, eleM }].
             * @example [
             *       {
             *         "distM": 0,
             *         "eleM": 34.2
             *       },
             *       {
             *         "distM": 1000,
             *         "eleM": 41.7
             *       },
             *       {
             *         "distM": 2000,
             *         "eleM": 38.1
             *       }
             *     ]
             */
            elevationProfile?: {
                distM?: number;
                eleM?: number;
            }[] | null;
            /**
             * @description True when visibility is 'public'; drives the Explore feed.
             * @example true
             */
            isPublic: boolean;
            /** @example 2026-06-01T08:30:00.000Z */
            createdAt: string;
            /** @example 2026-06-01T08:30:00.000Z */
            updatedAt: string;
            /** @description Matchable segments (PoC default: the full-route segment). */
            segments: components["schemas"]["SegmentDto"][];
            /**
             * @description Number of JOINED members on this route.
             * @example 3
             */
            memberCount: number;
        };
        UpdateRouteRequestDto: {
            /** @example Riverside loop */
            name?: string;
            /** @example Flat 5k along the river path. */
            description?: string;
            /**
             * @example invite
             * @enum {string}
             */
            visibility?: "private" | "invite" | "public";
            geometry?: components["schemas"]["RouteGeometryRequestDto"];
        };
        ActivityElevationRequestDto: {
            /**
             * @description Cumulative elevation gain in meters.
             * @example 42.5
             */
            gainMeters: number;
        };
        ActivityPointRequestDto: {
            /**
             * @description Latitude (WGS84).
             * @example 37.7825
             */
            lat: number;
            /**
             * @description Longitude (WGS84).
             * @example -122.4012
             */
            lng: number;
            /**
             * @description Sample timestamp in epoch milliseconds.
             * @example 1717199990000
             */
            ts: number;
            /**
             * @description Elevation in meters.
             * @example 34.2
             */
            ele?: number;
            /**
             * @description GPS horizontal accuracy in meters.
             * @example 8
             */
            accuracy?: number;
        };
        CreateActivityRequestDto: {
            /**
             * @description Client-generated UUID v4 (idempotency key for the run).
             * @example a1b2c3d4-e5f6-4789-a012-3456789abcde
             */
            id: string;
            /** @example Morning run */
            title: string;
            /**
             * @example RUN
             * @enum {string}
             */
            type: "RUN" | "JOG" | "WALK";
            /**
             * @description Route this run was recorded against, or null.
             * @example route-uuid-7f3a
             */
            routeId?: string | null;
            /**
             * @description Recording start time, epoch milliseconds.
             * @example 1717199990000
             */
            startedAt: number;
            /**
             * @description Recording end time, epoch milliseconds.
             * @example 1717200600000
             */
            endedAt: number;
            /**
             * @description Elapsed duration in milliseconds.
             * @example 610000
             */
            durationMs: number;
            /**
             * @description Advisory distance in meters — the server recomputes from the track.
             * @example 5012.4
             */
            distanceMeters?: number;
            elevation: components["schemas"]["ActivityElevationRequestDto"];
            /** @description Recorded GPS samples ({lat,lng,ts}). Capped at 50,000. */
            points: components["schemas"]["ActivityPointRequestDto"][];
        };
        BestEffortResponseDto: {
            /** @example segment-uuid-9c1b */
            segmentId: string;
            /**
             * @description Elapsed time over the segment in milliseconds (BigInt as string).
             * @example 610000
             */
            elapsedMs: string;
            /**
             * @description Rank on the segment leaderboard (RANK() semantics).
             * @example 1
             */
            rank: number;
        };
        ActivityResponseDto: {
            /**
             * @description Client-generated UUID v4 (idempotency key for the whole run).
             * @example a1b2c3d4-e5f6-4789-a012-3456789abcde
             */
            id: string;
            /**
             * @description Owner User.id (= Firebase uid).
             * @example firebase-uid-abc123
             */
            userId: string;
            /**
             * @description Route this activity was recorded against, or null.
             * @example route-uuid-7f3a
             */
            routeId?: Record<string, never> | null;
            /** @example Morning run */
            title: string;
            /**
             * @description Activity type.
             * @example RUN
             * @enum {string}
             */
            type: "RUN" | "JOG" | "WALK";
            /** @example 2026-06-01T08:30:00.000Z */
            startedAt: string;
            /** @example 2026-06-01T08:30:00.000Z */
            endedAt: string;
            /**
             * @description Elapsed duration in milliseconds (BigInt serialized as string).
             * @example 610000
             */
            durationMs: string;
            /**
             * @description Total distance in meters (server-recomputed via ST_Length(track::geography)).
             * @example 5012.4
             */
            distanceM: number;
            /**
             * @description Cumulative elevation gain in meters.
             * @example 42.5
             */
            elevationGainM?: Record<string, never> | null;
            /**
             * @description Average pace in seconds per kilometer.
             * @example 365.4
             */
            avgPaceSPerKm?: Record<string, never> | null;
            /** @description Recorded track as a GeoJSON LineString (WGS84, [lng, lat]), or null. */
            track?: components["schemas"]["GeoJsonLineStringDto"] | null;
            /** @example 2026-06-01T08:30:00.000Z */
            createdAt: string;
            /** @example 2026-06-01T08:30:00.000Z */
            updatedAt: string;
            /** @description Best efforts matched on save (empty until segment matching ships in CP3). */
            bestEfforts: components["schemas"]["BestEffortResponseDto"][];
        };
        ActivityDto: {
            /**
             * @description Client-generated UUID v4 (idempotency key for the whole run).
             * @example a1b2c3d4-e5f6-4789-a012-3456789abcde
             */
            id: string;
            /**
             * @description Owner User.id (= Firebase uid).
             * @example firebase-uid-abc123
             */
            userId: string;
            /**
             * @description Route this activity was recorded against, or null.
             * @example route-uuid-7f3a
             */
            routeId?: Record<string, never> | null;
            /** @example Morning run */
            title: string;
            /**
             * @description Activity type.
             * @example RUN
             * @enum {string}
             */
            type: "RUN" | "JOG" | "WALK";
            /** @example 2026-06-01T08:30:00.000Z */
            startedAt: string;
            /** @example 2026-06-01T08:30:00.000Z */
            endedAt: string;
            /**
             * @description Elapsed duration in milliseconds (BigInt serialized as string).
             * @example 610000
             */
            durationMs: string;
            /**
             * @description Total distance in meters (server-recomputed via ST_Length(track::geography)).
             * @example 5012.4
             */
            distanceM: number;
            /**
             * @description Cumulative elevation gain in meters.
             * @example 42.5
             */
            elevationGainM?: Record<string, never> | null;
            /**
             * @description Average pace in seconds per kilometer.
             * @example 365.4
             */
            avgPaceSPerKm?: Record<string, never> | null;
            /** @description Recorded track as a GeoJSON LineString (WGS84, [lng, lat]), or null. */
            track?: components["schemas"]["GeoJsonLineStringDto"] | null;
            /** @example 2026-06-01T08:30:00.000Z */
            createdAt: string;
            /** @example 2026-06-01T08:30:00.000Z */
            updatedAt: string;
        };
        ActivityListResponseDto: {
            items: components["schemas"]["ActivityDto"][];
            /**
             * @description Cursor for the next page, or null if there are no more rows.
             * @example a1b2c3d4-e5f6-4789-a012-3456789abcde
             */
            nextCursor?: string | null;
        };
        DeleteActivityResponseDto: {
            /**
             * @description Id of the deleted activity.
             * @example a1b2c3d4-e5f6-4789-a012-3456789abcde
             */
            id: string;
            /** @example true */
            deleted: boolean;
        };
        InviteMemberRequestDto: {
            /**
             * @description Email of the person to invite. Linked to their User if one exists, otherwise held as a pending email invite.
             * @example bob@example.com
             */
            email: string;
        };
        MembershipUserDto: {
            /**
             * @description Internal id (= Firebase uid).
             * @example firebase-uid-abc123
             */
            id: string;
            /** @example alice@example.com */
            email: string;
            /** @example Alice Runner */
            displayName?: Record<string, never> | null;
            /** @example https://example.com/avatars/alice.png */
            photoUrl?: Record<string, never> | null;
        };
        MembershipResponseDto: {
            /** @example membership-uuid-4d2e */
            id: string;
            /**
             * @description Route this membership belongs to.
             * @example route-uuid-7f3a
             */
            routeId: string;
            /**
             * @description Linked User.id; null while an email invite is unclaimed.
             * @example firebase-uid-abc123
             */
            userId?: string | null;
            /**
             * @example MEMBER
             * @enum {string}
             */
            role: "OWNER" | "MEMBER";
            /**
             * @example INVITED
             * @enum {string}
             */
            status: "INVITED" | "JOINED" | "DECLINED";
            /**
             * @description User.id of the inviter (route owner), or null.
             * @example firebase-uid-abc123
             */
            invitedById?: string | null;
            /**
             * @description Email the invite was addressed to.
             * @example bob@example.com
             */
            invitedEmail?: string | null;
            /** @description Linked user identity; null for an unclaimed email invite. */
            user?: components["schemas"]["MembershipUserDto"] | null;
            /** @example 2026-06-01T08:30:00.000Z */
            createdAt: string;
            /** @example 2026-06-01T08:30:00.000Z */
            updatedAt: string;
        };
        RouteMembershipDto: {
            /** @example membership-uuid-4d2e */
            id: string;
            /**
             * @description Route this membership belongs to.
             * @example route-uuid-7f3a
             */
            routeId: string;
            /**
             * @description Linked User.id; null while an email invite is unclaimed.
             * @example firebase-uid-abc123
             */
            userId?: string | null;
            /**
             * @example MEMBER
             * @enum {string}
             */
            role: "OWNER" | "MEMBER";
            /**
             * @example INVITED
             * @enum {string}
             */
            status: "INVITED" | "JOINED" | "DECLINED";
            /**
             * @description User.id of the inviter (route owner), or null.
             * @example firebase-uid-abc123
             */
            invitedById?: string | null;
            /**
             * @description Email the invite was addressed to.
             * @example bob@example.com
             */
            invitedEmail?: string | null;
            /** @description Linked user identity; null for an unclaimed email invite. */
            user?: components["schemas"]["MembershipUserDto"] | null;
            /** @example 2026-06-01T08:30:00.000Z */
            createdAt: string;
            /** @example 2026-06-01T08:30:00.000Z */
            updatedAt: string;
        };
        MemberListResponseDto: {
            /** @description All memberships on the route, oldest first. */
            members: components["schemas"]["RouteMembershipDto"][];
        };
        InviteListResponseDto: {
            /** @description The caller's pending invites (status INVITED), newest first. */
            invites: components["schemas"]["RouteMembershipDto"][];
        };
        LeaderboardEntryResponseDto: {
            /**
             * @description Rank (RANK() semantics).
             * @example 1
             */
            rank: number;
            /**
             * @description Athlete (User) id.
             * @example firebase-uid-abc123
             */
            userId: string;
            /**
             * @description Activity that set this best effort.
             * @example a1b2c3d4-e5f6-4789-a012-3456789abcde
             */
            activityId: string;
            /**
             * @description Best elapsed time over the segment in milliseconds (BigInt as string).
             * @example 610000
             */
            elapsedMs: string;
            /**
             * @description When the effort’s activity started.
             * @example 2026-06-01T08:30:00.000Z
             */
            startedAt: string;
            /**
             * @description Distinct athletes with a qualifying effort for the period.
             * @example 12
             */
            totalAthletes: number;
        };
        LeaderboardResponseDto: {
            /**
             * @description Segment the leaderboard is scoped to.
             * @example segment-uuid-9c1b
             */
            segmentId: string;
            /**
             * @description Time window applied to the efforts (`all` | `month` | `week`).
             * @example all
             */
            period: string;
            /**
             * @description Distinct athletes with a qualifying effort for the period (0 when empty).
             * @example 12
             */
            totalAthletes: number;
            entries: components["schemas"]["LeaderboardEntryResponseDto"][];
            /**
             * @description Cursor for the next page, or null when there are no more rows.
             * @example 20
             */
            nextCursor?: string | null;
        };
        MyLeaderboardEntryResponseDto: {
            /**
             * @description Segment the rank is scoped to.
             * @example segment-uuid-9c1b
             */
            segmentId: string;
            /**
             * @description Time window applied to the efforts (`all` | `month` | `week`).
             * @example all
             */
            period: string;
            /**
             * @description Distinct athletes with a qualifying effort for the period (0 when empty).
             * @example 12
             */
            totalAthletes: number;
            /** @description The caller’s best ranked effort, or null when they have none. */
            entry?: components["schemas"]["LeaderboardEntryResponseDto"] | null;
        };
        SnapPointRequestDto: {
            /**
             * @description Latitude (WGS84).
             * @example 37.7825
             */
            lat: number;
            /**
             * @description Longitude (WGS84).
             * @example -122.4012
             */
            lng: number;
        };
        SnapRouteRequestDto: {
            /** @description Drawn polyline anchors ({lat,lng}); ≥ 2 points. */
            points: components["schemas"]["SnapPointRequestDto"][];
            /**
             * @description Routing profile; defaults to the server-configured GRAPHHOPPER_PROFILE (car).
             * @example car
             */
            profile?: string;
        };
        SnapResponseDto: {
            /**
             * @description True when the polyline was snapped to roads by GraphHopper; false in degraded mode.
             * @example true
             */
            snapped: boolean;
            /** @description Snapped path (snapped:true) or the original drawn polyline (degraded), as a GeoJSON LineString (WGS84, [lng, lat]). */
            geometry: components["schemas"]["GeoJsonLineStringDto"];
            /**
             * @description Path length in meters: GraphHopper paths[0].distance when snapped, else the haversine sum of the input.
             * @example 5012.4
             */
            distanceM: number;
            /**
             * @description Present only in degraded mode; the only value is 'ROUTING_UNAVAILABLE'.
             * @example ROUTING_UNAVAILABLE
             */
            reason?: string;
        };
        LiveSessionResponseDto: {
            /**
             * @description RTDB node to subscribe to for every runner on the route (`liveSessions/<routeId>`).
             * @example liveSessions/route-uuid-7f3a
             */
            rtdbPath: string;
            /**
             * @description The caller’s own write subtree (`liveSessions/<routeId>/<uid>`) — overwrite only this node.
             * @example liveSessions/route-uuid-7f3a/firebase-uid-abc123
             */
            selfPath: string;
            /**
             * @description Presence node for the route (`presence/<routeId>`).
             * @example presence/route-uuid-7f3a
             */
            presencePath: string;
            /**
             * @description Suggested session lifetime in seconds before re-authorizing.
             * @example 3600
             */
            ttlSeconds: number;
            /**
             * @description Minimum interval between position overwrites in milliseconds (LIVE_THROTTLE_MS).
             * @example 2000
             */
            throttleMs: number;
            /**
             * @description Hard per-route live participant cap (LIVE_MAX_PARTICIPANTS); past it the endpoint returns 429 live_full.
             * @example 25
             */
            maxParticipants: number;
        };
        LiveParticipantResponseDto: {
            /**
             * @description Participant (User) id / uid.
             * @example firebase-uid-abc123
             */
            userId: string;
            /**
             * @description Participant display name (from presence), or null.
             * @example Alice Runner
             */
            displayName?: string | null;
            /**
             * @description Participant photo URL (from presence), or null.
             * @example https://example.com/avatars/alice.png
             */
            photoUrl?: string | null;
            /**
             * @description Presence state (`running` | `paused`).
             * @example running
             */
            state: string;
            /**
             * @description Whether the participant is currently online (presence.online).
             * @example true
             */
            online: boolean;
            /**
             * @description Last known latitude, or null when no position is available.
             * @example 37.7825
             */
            lat?: number | null;
            /**
             * @description Last known longitude, or null when no position is available.
             * @example -122.4012
             */
            lng?: number | null;
            /**
             * @description Epoch-ms timestamp of the last seen position, or null.
             * @example 1717199990000
             */
            lastSeen?: number | null;
        };
        LiveParticipantsResponseDto: {
            /**
             * @description Route id.
             * @example route-uuid-7f3a
             */
            routeId: string;
            /**
             * @description RTDB node the client should subscribe to (`liveSessions/<routeId>`).
             * @example liveSessions/route-uuid-7f3a
             */
            rtdbPath: string;
            /**
             * @description Whether the backend could read live state from RTDB (false when Firebase is not configured).
             * @example false
             */
            enabled: boolean;
            participants: components["schemas"]["LiveParticipantResponseDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    MainController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    AuthController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    AuthController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    StatsController_getSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsSummaryResponseDto"];
                };
            };
        };
    };
    RoutesController_list: {
        parameters: {
            query?: {
                /** @description Which set of routes to list (default `mine`). */
                scope?: "mine" | "member" | "public";
                /** @description Max rows to return (default 20, max 100). */
                limit?: number;
                /** @description Opaque cursor: the id of the last route from the previous page. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteListResponseDto"];
                };
            };
        };
    };
    RoutesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRouteRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponseDto"];
                };
            };
        };
    };
    RoutesController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteDetailResponseDto"];
                };
            };
        };
    };
    RoutesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoutesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRouteRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponseDto"];
                };
            };
        };
    };
    ActivitiesController_listMine: {
        parameters: {
            query?: {
                /** @description Max rows to return (default 20, max 100). */
                limit?: number;
                /** @description Opaque cursor — the id of the last activity from the previous page. */
                cursor?: string;
                /** @description Restrict to activities recorded against this route. */
                routeId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityListResponseDto"];
                };
            };
        };
    };
    ActivitiesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivityRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponseDto"];
                };
            };
        };
    };
    ActivitiesController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity id (client-generated UUID). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponseDto"];
                };
            };
        };
    };
    ActivitiesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity id (client-generated UUID). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteActivityResponseDto"];
                };
            };
        };
    };
    RouteActivitiesController_listForRoute: {
        parameters: {
            query?: {
                /** @description Max rows to return (default 20, max 100). */
                limit?: number;
                /** @description Opaque cursor — the id of the last activity from the previous page. */
                cursor?: string;
            };
            header?: never;
            path: {
                /** @description Route id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityListResponseDto"];
                };
            };
        };
    };
    RouteMembersController_invite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponseDto"];
                };
            };
        };
    };
    RouteMembersController_listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberListResponseDto"];
                };
            };
        };
    };
    RouteMembersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route id. */
                id: string;
                /** @description User.id to remove; equals the caller when leaving. */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membership removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitesController_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteListResponseDto"];
                };
            };
        };
    };
    InvitesController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description RouteMembership id. */
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponseDto"];
                };
            };
        };
    };
    InvitesController_decline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description RouteMembership id. */
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponseDto"];
                };
            };
        };
    };
    SegmentLeaderboardController_getLeaderboard: {
        parameters: {
            query?: {
                /** @description Max ranked rows to return (default 20, max 100). */
                limit?: number;
                /** @description Opaque cursor from the previous page’s `nextCursor`, or null/omitted for the first page. */
                cursor?: string;
                /** @description Time window for ranked efforts (default `all`). */
                period?: "all" | "month" | "week";
            };
            header?: never;
            path: {
                /** @description Segment id. */
                segmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardResponseDto"];
                };
            };
        };
    };
    SegmentLeaderboardController_getMyEntry: {
        parameters: {
            query?: {
                /** @description Max ranked rows to return (default 20, max 100). */
                limit?: number;
                /** @description Opaque cursor from the previous page’s `nextCursor`, or null/omitted for the first page. */
                cursor?: string;
                /** @description Time window for ranked efforts (default `all`). */
                period?: "all" | "month" | "week";
            };
            header?: never;
            path: {
                /** @description Segment id. */
                segmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyLeaderboardEntryResponseDto"];
                };
            };
        };
    };
    RouteLeaderboardController_getRouteLeaderboard: {
        parameters: {
            query?: {
                /** @description Max ranked rows to return (default 20, max 100). */
                limit?: number;
                /** @description Opaque cursor from the previous page’s `nextCursor`, or null/omitted for the first page. */
                cursor?: string;
                /** @description Time window for ranked efforts (default `all`). */
                period?: "all" | "month" | "week";
            };
            header?: never;
            path: {
                /** @description Route id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardResponseDto"];
                };
            };
        };
    };
    RoutingController_snap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapRouteRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapResponseDto"];
                };
            };
        };
    };
    RouteLiveController_startSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveSessionResponseDto"];
                };
            };
            /** @description Route is at LIVE_MAX_PARTICIPANTS — `{ reason: "live_full" }`. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RouteLiveController_listParticipants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Route id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveParticipantsResponseDto"];
                };
            };
        };
    };
}
